Repository retaildevcrews/ngsa, pull requests merged in 2020-12, with the labels that each got.

#161 AKS Script
  IaC/AKS/cluster/charts/loderunner/helm-config.example.yaml
  IaC/AKS/cluster/charts/loderunner/values.yaml
  IaC/AKS/cluster/charts/ngsa/helm-config.example.yaml
  IaC/AKS/cluster/charts/ngsa/templates/certificate.yaml
  IaC/AKS/cluster/charts/ngsa/values.yaml
  IaC/scripts/create-cluster-env.bash
Labels: IaC

#163 Feature/147 AKS script documentation
  IaC/AKS/README.md
Labels: Documentation, IaC

#215 Updated image build workflow to support semver tagging
  .github/workflows/ngsa.yaml
Labels: CI/CD

#214 CVector / Trace Header updates
  spikes/data/dataservice/app/DataAccessLayer/InMemoryDal.cs
  spikes/data/dataservice/app/DataAccessLayer/dalMovies.cs
  spikes/data/dataservice/app/Middleware/RequestLogger/logger.cs
  spikes/data/dataservice/app/ds.csproj
  spikes/data/dataservice/dataservice.sln
  spikes/data/dataservice/tests/tests.csproj
  spikes/data/loderunner/app/WebValidation/Main.cs
  spikes/data/loderunner/app/WebValidation/Model/PerfLog.cs
  spikes/data/loderunner/app/loderunner.csproj
  spikes/data/ngsa-csharp/app/Middleware/RequestLogger/logger.cs
  spikes/data/ngsa-csharp/app/ngsa.csproj
  spikes/data/ngsa-csharp/ngsa.sln
  spikes/data/ngsa-csharp/tests/AppTests.cs
  spikes/data/shared/CVectorExtensions.cs
  spikes/data/shared/CVectorHttpExtensions.cs
Labels: InternalFeedback, LoadClient, PlatValidApp

#216 Fixed app version for docker tags
  .github/workflows/ngsa.yaml
Labels: CI/CD

#236 updated test files
  src/loderunner/app/baseline.json
  src/loderunner/app/benchmark.json
Labels: LoadClient

#234 DS update
  spikes/data/dataservice/app/DataAccessLayer/InMemoryDal.cs
  spikes/data/dataservice/app/DataAccessLayer/dalActors.cs
  spikes/data/dataservice/app/DataAccessLayer/dalMovies.cs
Labels: PlatValidApp

#238 Doc updates
  .gdn/README.md
  .github/README.md
  .github/workflows/README.md
  .github/workflows/mdlinkcheck.yaml
  .github/workflows/scheduled_mdlinkcheck.yaml
  IaC/BareMetal/README.md
  IaC/BareMetal/app/README.md
  IaC/BareMetal/app/baseline.yaml
  IaC/BareMetal/app/benchmark.yaml
  IaC/BareMetal/app/config.yaml
  IaC/BareMetal/app/in-memory.yaml
  IaC/BareMetal/app/l8r.yaml
  IaC/BareMetal/app/lb.yaml
  IaC/BareMetal/app/ngsa.yaml
  IaC/BareMetal/fluentbit/in-memory.yaml
  IaC/BareMetal/metalLB.yaml
  IaC/BareMetal/setup-letsencrypt.md
  IaC/BareMetal/setup-nginx.md
  IaC/README.md
  IaC/scripts/README.md
  README.md
  TestFiles/README.md
  docs/ApplicationArch.md
  docs/CICD.md
  docs/Developer.md
  docs/EngineeringPractices.md
  docs/README.md
  docs/images/ngsa-app-deploy-top.png
  spikes/README.md
  spikes/sidecar/README.md
  spikes/sidecar/baseline.yaml
  spikes/sidecar/benchmark.yaml
  spikes/sidecar/config.yaml
  spikes/sidecar/in-memory.yaml
  spikes/sidecar/ngsa.yaml
  spikes/sidecar/role.yaml
  spikes/sidecar/webv.yaml
  src/README.md
  src/loderunner/README.md
  src/ngsa/README.md
Labels: DevExperience, Documentation

#237 data service - new command line options
  spikes/data/dataservice/app/Core/CommandLine.cs
  spikes/data/dataservice/app/Core/CommandLineExtensions.cs
  spikes/data/dataservice/app/DataAccessLayer/InMemoryDal.cs
  spikes/data/dataservice/app/DataAccessLayer/Model/GenreObject.cs
  spikes/data/dataservice/app/Program.cs
  spikes/data/dataservice/tests/AppTests.cs
Labels: DesignReview, PlatValidApp

#246 fixed merge error
  NewApp/ngsa-csharp/Imdb.Model/GenreObject.cs
Labels: Bug

#252 update ci-cd to use loderunner
  .github/workflows/ngsa.yaml
  NewApp/ngsa-csharp/Ngsa.LodeRunner/WebValidation/Main.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/baseline.json
  NewApp/ngsa-csharp/Ngsa.LodeRunner/benchmark.json
  NewApp/ngsa-csharp/Ngsa.LodeRunner/direct-read.json
  NewApp/ngsa-csharp/Ngsa.LodeRunner/genre.json
  NewApp/ngsa-csharp/Ngsa.LodeRunner/rating.json
  NewApp/ngsa-csharp/Ngsa.LodeRunner/year.json
  TestFiles/README.md
  TestFiles/baseline.json
  TestFiles/perfTargets.txt
  src/loderunner/app/WebValidation/Main.cs
  src/loderunner/app/benchmark.json
  src/loderunner/app/direct-read.json
  src/loderunner/app/genre.json
  src/loderunner/app/rating.json
  src/loderunner/app/year.json
Labels: CI-CD, CI/CD

#249 renamed GenreObject
  NewApp/ngsa-csharp/Imdb.Model/Genre.cs
  NewApp/ngsa-csharp/Imdb.Model/Imdb.Model.csproj
  NewApp/ngsa-csharp/Ngsa.Dataservice/DataAccessLayer/InMemoryDal.cs
Labels: DataService

#227 Migrated ngsa helm chart to ngsa-cd repo and updated docs
  IaC/AKS/README.md
  IaC/AKS/cluster/charts/ngsa/.helmignore
  IaC/AKS/cluster/charts/ngsa/Chart.yaml
  IaC/AKS/cluster/charts/ngsa/helm-config.example.yaml
  IaC/AKS/cluster/charts/ngsa/templates/_helpers.tpl
  IaC/AKS/cluster/charts/ngsa/templates/certificate.yaml
  IaC/AKS/cluster/charts/ngsa/templates/configmap.yaml
  IaC/AKS/cluster/charts/ngsa/templates/deployment.yaml
  IaC/AKS/cluster/charts/ngsa/templates/gateway.yaml
  IaC/AKS/cluster/charts/ngsa/templates/scaledobject.yaml
  IaC/AKS/cluster/charts/ngsa/templates/service.yaml
  IaC/AKS/cluster/charts/ngsa/templates/serviceaccount.yaml
  IaC/AKS/cluster/charts/ngsa/templates/virtualservice.yaml
  IaC/AKS/cluster/charts/ngsa/values.yaml
Labels: Documentation

#254 Add alert documentation
  docs/Alerts.md
Labels: Alert, Documentation, Observability

#255 updated swagger path again
  NewApp/ngsa-csharp/Ngsa.App/Core/Constants.cs
Labels: Bug, PlatValidApp

#257 Update Dockerfiles
  NewApp/ngsa-csharp/Ngsa.App/Dockerfile
  NewApp/ngsa-csharp/Ngsa.App/Ngsa.App.csproj
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/AppTests.cs
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/Ngsa.DataService.Tests.csproj
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/README.md
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/runtests
  NewApp/ngsa-csharp/Ngsa.DataService/Controllers/ActorsController.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Controllers/FeaturedController.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Controllers/GenresController.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Controllers/MoviesController.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Controllers/ResultHandler.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Core/CommandLine.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Core/Constants.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Core/Secrets.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Core/ascii-art.txt
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/CosmosConfig.cs
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/InMemoryDal.cs
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/dalActors.cs
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/dalGenres.cs
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/dalMain.cs
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/dalMovies.cs
  NewApp/ngsa-csharp/Ngsa.DataService/DataAccessLayer/idal.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Dockerfile
  NewApp/ngsa-csharp/Ngsa.DataService/Ngsa.DataService.csproj
  NewApp/ngsa-csharp/Ngsa.DataService/Program.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Startup.cs
  NewApp/ngsa-csharp/Ngsa.DataService/appsettings.Development.json
  NewApp/ngsa-csharp/Ngsa.DataService/appsettings.json
  NewApp/ngsa-csharp/Ngsa.DataService/data/actors.json
  NewApp/ngsa-csharp/Ngsa.DataService/data/featured.json
  NewApp/ngsa-csharp/Ngsa.DataService/data/genres.json
  NewApp/ngsa-csharp/Ngsa.DataService/data/movies.json
  NewApp/ngsa-csharp/Ngsa.DataService/secrets/CosmosCollection
  NewApp/ngsa-csharp/Ngsa.DataService/secrets/CosmosDatabase
  NewApp/ngsa-csharp/Ngsa.DataService/secrets/CosmosUrl
  NewApp/ngsa-csharp/Ngsa.LodeRunner/Dockerfile
Labels: CI-CD, CI/CD, DataService, Loderunner, PlatValidApp

#274 New ci-cd
  .github/workflows/NewApp.yaml
  NewApp/ngsa-csharp/Ngsa.App.Tests/AppTests.cs
  NewApp/ngsa-csharp/Ngsa.App.Tests/runtests.sh
  NewApp/ngsa-csharp/Ngsa.App/Controllers/DataService.cs
  NewApp/ngsa-csharp/Ngsa.App/Core/CommandLine.cs
  NewApp/ngsa-csharp/Ngsa.App/Dockerfile
  NewApp/ngsa-csharp/Ngsa.App/Program.cs
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/AppTests.cs
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/runtests
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/runtests.sh
  NewApp/ngsa-csharp/Ngsa.DataService/Core/CommandLine.cs
  NewApp/ngsa-csharp/Ngsa.DataService/Dockerfile
  NewApp/ngsa-csharp/Ngsa.DataService/Program.cs
  NewApp/ngsa-csharp/Ngsa.Middleware/QueryParameters/ActorExtensions.cs
  NewApp/ngsa-csharp/Ngsa.Middleware/QueryParameters/Validation/ValidationResult.cs
  NewApp/ngsa-csharp/test-ci-cd.txt
Labels: Bug, CI-CD, CI/CD

#280 added check for draft PR
  .github/workflows/NewApp.yaml
Labels: CI-CD, CI/CD
