Repository retaildevcrews/ngsa, pull requests merged in 2020-11, with the labels that each got.

#82 update nginx setup
  .gitconfig
  IaC/BareMetal/README.md
  IaC/BareMetal/setup-letsencrypt.md
  IaC/BareMetal/setup-nginx.md
  IaC/BareMetal/template.conf
  IaC/BareMetal/webv-agent.yml
  IaC/BareMetal/webv.yml
Labels: Bug, Documentation

#96 Naming convention
  docs/NamingConvention.md
Labels: Documentation

#109 fixed ci-cd bug
  .github/workflows/log-agent.yaml
  .github/workflows/ngsa.yaml
Labels: Bug

#99 Update Docs for preprod setup
  .gitignore
  IaC/AKS/README.md
  IaC/AKS/cluster/charts/ngsa/helm-config.example.yaml
  IaC/AKS/cluster/charts/ngsa/templates/config.yaml
  IaC/AKS/cluster/charts/ngsa/templates/deployment.yaml
  IaC/AKS/cluster/charts/ngsa/templates/role.yaml
  IaC/AKS/cluster/charts/ngsa/templates/scaledobject.yaml
  IaC/AKS/cluster/charts/ngsa/templates/virtualservice.yaml
  IaC/AKS/cluster/charts/ngsa/values.yaml
  IaC/AKS/cluster/charts/smoker/templates/config.yaml
  IaC/AKS/cluster/charts/smoker/templates/role.yaml
  IaC/AKS/cluster/charts/smoker/templates/smoker-deployment.yaml
  IaC/AKS/cluster/charts/smoker/templates/smoker-job.yaml
  IaC/AKS/cluster/charts/smoker/values.yaml
  IaC/scripts/smokers.sh
Labels: Documentation

#108 update tests for consistency
  IaC/BareMetal/README.md
  IaC/BareMetal/sidecar/webv.yml
  TestFiles/benchmark.json
  TestFiles/genre.json
  TestFiles/merge.cs
  TestFiles/merge.csproj
  TestFiles/rating.json
  TestFiles/year.json
  src/log-agent/core/LogHandler.cs
  src/ngsa/app/Core/CommandLine.cs
  src/ngsa/app/DataAccessLayer/InMemoryDal.cs
  src/ngsa/app/Middleware/RequestLogger/logger.cs
  src/ngsa/app/Program.cs
  src/ngsa/app/secrets/CosmosUrl
Labels: LoadClient, Testing:Load, Testing:Perf

#111 fixed version
  src/ngsa/app/ngsa.csproj
Labels: Bug

#124 Add Observability/dashboard documentation
  .gitignore
  docs/NGSA_Dashboard_Template.json
  docs/Observability.md
Labels: Dashboard, Documentation

#140 Fixing md linter errors
  docs/EngineeringPractices.md
  docs/NamingConvention.md
  docs/Observability.md
  docs/WorkingAgreement.md
  spikes/grafana-az-monitor/README.md
  spikes/istio-multicluster/README.md
Labels: Bug, Documentation

#129 Doc changes based on dev cluster setup
  IaC/AKS/README.md
  IaC/AKS/cluster/charts/ngsa/templates/config.yaml
  IaC/AKS/cluster/charts/ngsa/templates/deployment.yaml
  IaC/AKS/cluster/charts/ngsa/templates/role.yaml
  IaC/AKS/cluster/charts/ngsa/templates/serviceaccount.yaml
  IaC/AKS/cluster/charts/ngsa/values.yaml
  IaC/AKS/cluster/charts/smoker/helm-config.example.yaml
Labels: Documentation

#143 Initial fluent bit implementation
  IaC/BareMetal/README.md
  IaC/BareMetal/fluentbit/account-fluentbit.yaml
  IaC/BareMetal/fluentbit/dbg/README.md
  IaC/BareMetal/fluentbit/dbg/apply-config
  IaC/BareMetal/fluentbit/dbg/apply-la
  IaC/BareMetal/fluentbit/dbg/apply-stdout
  IaC/BareMetal/fluentbit/dbg/fluentbit-debug.yaml
  IaC/BareMetal/fluentbit/dbg/la-config-debug.yaml
  IaC/BareMetal/fluentbit/dbg/role-fluentbit-debug.yaml
  IaC/BareMetal/fluentbit/dbg/stdout-config-debug.yaml
  IaC/BareMetal/fluentbit/dbg/zone-config-debug.yaml
  IaC/BareMetal/multipass/README.md
  IaC/BareMetal/setup-letsencrypt.md
  IaC/BareMetal/setup-nginx.md
  spikes/fluentd/README.md
  spikes/fluentd/account-fluentd.yaml
  spikes/fluentd/apply-config
  spikes/fluentd/config-fluentd.yaml
  spikes/fluentd/dbg/README.md
  spikes/fluentd/dbg/apply-config
  spikes/fluentd/dbg/baseline-debug.yaml
  spikes/fluentd/dbg/config-fluentd-debug.yaml
  spikes/fluentd/dbg/delete-fluentd
  spikes/fluentd/dbg/fluentd-debug.yaml
  spikes/fluentd/dbg/in-memory-debug.yaml
  spikes/fluentd/dbg/role-fluentd-debug.yaml
  spikes/fluentd/dbg/zone-config-debug.yaml
  spikes/fluentd/fluentd-deamonset.yaml
  spikes/fluentd/image-fluentd/Dockerfile
  spikes/fluentd/image-fluentd/Gemfile
  spikes/fluentd/image-fluentd/Makefile
  spikes/fluentd/image-fluentd/README.md
  spikes/fluentd/image-fluentd/entrypoint.sh
  spikes/fluentd/image-fluentd/fluent.conf
  src/ngsa/app/Middleware/RequestLogger/logger.cs
Labels: Observability, Observe

#151 Added CPR Demo
  IaC/BareMetal/README.md
  IaC/BareMetal/cpr-demo/breakit.yaml
  IaC/BareMetal/cpr-demo/stress.yaml
  IaC/BareMetal/cpr-demo/webv.yaml
  IaC/BareMetal/fluentbit/dbg/README.md
  IaC/BareMetal/multipass/README.md
  IaC/BareMetal/multipass/src/daemon.json
  IaC/BareMetal/multipass/src/k8s.sh
  IaC/BareMetal/setup-letsencrypt.md
  spikes/sidecar/README.md
  spikes/sidecar/baseline.yml
  spikes/sidecar/benchmark.yml
  spikes/sidecar/config.yml
  spikes/sidecar/in-memory.yml
  spikes/sidecar/ngsa.yml
  spikes/sidecar/role.yml
  spikes/sidecar/webv.yml
Labels: CPR, Observability, Observe

#170 Fixed dead link for Istio shared install
  spikes/istio-multicluster/README.md
Labels: Bug, Documentation
