Repository retaildevcrews/ngsa, pull requests merged in 2020-10, with the labels that each got.

#26 Updated dead link check
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/workflows/appPR.yaml
  docs/HttpErrorResponses.md
  mlc_config.json
  src/tests/runtests
Labels: CI/CD

#31 Update userstory.md
  .github/ISSUE_TEMPLATE/userstory.md
Labels: Process

#38 Update WorkingAgreement.md
  docs/WorkingAgreement.md
Labels: Process

#39 Update WorkingAgreement.md
  docs/WorkingAgreement.md
Labels: Process

#40 Update task.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Process

#78 doc updates
  .gdn/r/.gdntoolsdata
  IaC/BareMetal/README.md
  IaC/BareMetal/multipass/README.md
  IaC/BareMetal/multipass/daemon.json
  IaC/BareMetal/multipass/k8s.sh
  IaC/BareMetal/multipass/k8s.yaml
  IaC/BareMetal/setup-bare-metal-vm.md
  src/tests/runtests
Labels: DevExperience, DevOps

#81 updated links in md
  .github/ISSUE_TEMPLATE/EngineeringFundChecklist.md
Labels: Bug, Documentation

#80 Adding smokers setup + other lint fixes
  IaC/AKS/README.md
  IaC/AKS/cluster/charts/ngsa/helm-config.yaml
  IaC/AKS/cluster/charts/ngsa/values.yaml
  IaC/AKS/cluster/charts/smoker/.helmignore
  IaC/AKS/cluster/charts/smoker/Chart.yaml
  IaC/AKS/cluster/charts/smoker/templates/NOTES.txt
  IaC/AKS/cluster/charts/smoker/templates/_helpers.tpl
  IaC/AKS/cluster/charts/smoker/templates/smoker-job.yaml
  IaC/AKS/cluster/charts/smoker/values.yaml
  IaC/scripts/smokers.sh
Labels: Documentation

#88 DNS and SSL/TLS setup for AKS
  IaC/AKS/README.md
  IaC/AKS/cluster/charts/ngsa/helm-config.yaml
  IaC/AKS/cluster/charts/ngsa/templates/certificate.yaml
  IaC/AKS/cluster/charts/ngsa/templates/gateway.yaml
  IaC/AKS/cluster/charts/ngsa/values.yaml
  IaC/AKS/cluster/manifests/cert-manager/clusterissuer.yaml
Labels: Documentation

#95 added correlation vector support
  src/app/DataAccessLayer/InMemoryDal.cs
  src/app/Middleware/RequestLogger/logger.cs
  src/app/ngsa.csproj
Labels: PlatValidApp
