Repository retaildevcrews/ngsa, pull requests merged in 2021-01, with the labels that each got.

#290 change webv to loderunner
  .github/workflows/NewApp.yaml
  NewApp/ngsa-csharp/Ngsa.App.Tests/AppTests.cs
  NewApp/ngsa-csharp/Ngsa.App.Tests/README.md
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/AppTests.cs
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/CommandLineTests.cs
  NewApp/ngsa-csharp/Ngsa.DataService.Tests/README.md
  NewApp/ngsa-csharp/Ngsa.LodeRunner.Tests/Ngsa.LodeRunner.Tests.csproj
  NewApp/ngsa-csharp/Ngsa.LodeRunner.Tests/TestApp.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner.Tests/TestArrayValidator.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner.Tests/TestCommonValidator.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner.Tests/TestConstants.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner.Tests/TestObjectValidator.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/Ngsa.LodeRunner.csproj
  NewApp/ngsa-csharp/Ngsa.LodeRunner/Program.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Main.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/InputJson.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/JsonArray.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/JsonItem.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/JsonPropertyByIndex.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/PerfLog.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/PerfTarget.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/Request.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/TimerRequestState.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/Validation.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/ValidationResult.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Model/config.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/ReadValidateJson.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Validators/ParameterValidator.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Validators/ResponseValidator.cs
  NewApp/ngsa-csharp/Ngsa.LodeRunner/baseline.json
  NewApp/ngsa-csharp/Ngsa.LodeRunner/dataservice.json
  NewApp/ngsa-csharp/Ngsa.Middleware/QueryParameters/Validation/ValidationResult.cs
  NewApp/ngsa-csharp/README.md
Labels: Bug, DataService, Loderunner, PlatValidApp

#288 SPIKE: Kuma multi cluster service mesh
  spikes/kuma-multicluster/README.md
  spikes/kuma-multicluster/debug.yaml
  spikes/kuma-multicluster/diagram.png
  spikes/kuma-multicluster/mesh.yaml
  spikes/kuma-multicluster/namespace.yaml
  spikes/kuma-multicluster/ngsa.yaml
  spikes/kuma-multicluster/traffic_route.yaml
Labels: SPIKE

#283 use containerd for dev cluster
  IaC/BareMetal/README.md
  IaC/BareMetal/app/README.md
  IaC/BareMetal/app/config.yaml
  IaC/BareMetal/fluentbit/account-fluentbit.yaml
  IaC/BareMetal/fluentbit/apply-config
  IaC/BareMetal/fluentbit/config-fluentbit.yaml
  IaC/BareMetal/fluentbit/dbg/README.md
  IaC/BareMetal/fluentbit/dbg/in-memory-debug.yaml
  IaC/BareMetal/fluentbit/dbg/zone-config-debug.yaml
  IaC/BareMetal/fluentbit/fluentbit-ds.yaml
  IaC/BareMetal/fluentbit/in-memory.yaml
  IaC/BareMetal/fluentbit/ngsa.yaml
  IaC/BareMetal/metalLB.yaml
  IaC/BareMetal/setup-bare-metal-vm.md
  IaC/DevCluster/README.md
  IaC/DevCluster/app/README.md
  IaC/DevCluster/app/config.yaml
  IaC/DevCluster/app/in-memory.yaml
  IaC/DevCluster/app/ngsa.yaml
  IaC/DevCluster/fluentbit/README.md
  IaC/DevCluster/fluentbit/account.yaml
  IaC/DevCluster/fluentbit/fluentbit-pod.yaml
  IaC/DevCluster/fluentbit/loga-config.yaml
  IaC/DevCluster/fluentbit/stdout-config.yaml
  IaC/DevCluster/loderunner/baseline-cosmos.yaml
  IaC/DevCluster/loderunner/baseline-memory.yaml
  IaC/DevCluster/loderunner/benchmark-cosmos.yaml
  IaC/DevCluster/loderunner/benchmark-memory.yaml
  IaC/DevCluster/loderunner/loderunner.yaml
  spikes/DevCluster/README.md
  spikes/DevCluster/loadbalancer/lb.yaml
  spikes/DevCluster/loadbalancer/setup-letsencrypt.md
  spikes/DevCluster/loadbalancer/setup-nginx.md
  spikes/DevCluster/loadbalancer/template.conf
  spikes/DevCluster/multipass/README.md
  spikes/DevCluster/multipass/k8s.yaml
  spikes/DevCluster/multipass/src/daemon.json
  spikes/DevCluster/multipass/src/k8s.sh
  spikes/cpr-demo/breakit.yaml
  spikes/cpr-demo/l8r.yaml
  spikes/cpr-demo/stress.yaml
  spikes/logapp/Program.cs
  spikes/logapp/README.md
  spikes/logapp/logapp.csproj
Labels: DevExperience, Documentation, IaC, InternalFeedback, REFACTOR

#300 updated load test for demos
  IaC/LoadDemo/README.md
  IaC/LoadDemo/load-10.yaml
  IaC/LoadDemo/load-100.yaml
  IaC/LoadDemo/load-500.yaml
Labels: Loderunner, PointDev, TestLoad, Testing:Load, Testing:Perf

#301 Run Broken Links Check on Push and PR
  .github/workflows/mdlinkcheck.yaml
Labels: CI-CD, CI/CD, DevOps, Small

#310 added notes from triage
  notes.md
Labels: Documentation

#311 Doc updates
  .gdn/.gdnsettings
  .gdn/.gitignore
  .gdn/README.md
  .gdn/internal.gdnhistory
  .gdn/r/.gdntoolsdata
  .github/README.md
  .github/workflows/README.md
  IaC/AKS/README.md
  IaC/AKS/scripts/create-cluster-env.bash
  IaC/README.md
  IaC/scripts/README.md
  IaC/scripts/smokers.sh
  LICENSE
  NewApp/ngsa-csharp/Ngsa.App/README.md
  NewApp/ngsa-csharp/Ngsa.DataService/README.md
  README.md
  SECURITY.md
  SUPPORT.md
  docs/HttpErrorResponses.md
  docs/NamingConvention.md
  docs/ParameterValidation.md
  docs/README.md
  spikes/DevCluster/README.md
  spikes/DevCluster/sidecar/README.md
  spikes/DevCluster/sidecar/baseline.yaml
  spikes/DevCluster/sidecar/benchmark.yaml
  spikes/DevCluster/sidecar/config.yaml
  spikes/DevCluster/sidecar/in-memory.yaml
  spikes/DevCluster/sidecar/ngsa.yaml
  spikes/DevCluster/sidecar/role.yaml
  spikes/DevCluster/sidecar/webv.yaml
  spikes/OldSource/README.md
  spikes/OldSource/loderunner/README.md
  spikes/OldSource/loderunner/app/README.md
  spikes/README.md
  src/README.md
  src/ngsa-csharp/README.md
Labels: Documentation

#315 doc updates
  .github/workflows/ngsa.yaml
  IaC/LoadDemo/load-500.yaml
  docs/CICD.md
  docs/NamingConvention.md
  src/ngsa-csharp/Ngsa.App.Tests/AppTests.cs
  src/ngsa-csharp/Ngsa.DataService.Tests/AppTests.cs
  src/ngsa-csharp/run-coverage.sh
  src/ngsa-csharp/test-ci-cd.txt
Labels: Documentation

#316 Doc updates
  docs/ApplicationArch.md
  docs/images/ngsa-request-sequence.png
Labels: DevExperience, Documentation, XSmall

#321 Doc updates
  docs/ApplicationArch.md
  docs/NamingConvention.md
  docs/images/ngsa-request-sequence.png
Labels: Documentation

#323 fluent bit containerd spike
  spikes/fluentbit-containerd/1-fluentbit-sample.yaml
  spikes/fluentbit-containerd/2-log-map.yaml
  spikes/fluentbit-containerd/3-working-log.yaml
  spikes/fluentbit-containerd/4-working-message.yaml
  spikes/fluentbit-containerd/README.md
Labels: FluentBit, SPIKE

#334 coc updates
  IaC/AKS/README.md
  docs/Alerts.md
  docs/Observability.md
Labels: Documentation

#338 Log
  IaC/AKS/cluster/charts/fluentbit/templates/config.yaml
  IaC/DevCluster/app/new-in-memory.yaml
  IaC/DevCluster/fluentbit/loga-config.yaml
  IaC/DevCluster/fluentbit/stdout-config.yaml
  src/ngsa-csharp/Ngsa.App/Controllers/ActorsController.cs
  src/ngsa-csharp/Ngsa.App/Controllers/FeaturedController.cs
  src/ngsa-csharp/Ngsa.App/Controllers/GenresController.cs
  src/ngsa-csharp/Ngsa.App/Controllers/MoviesController.cs
  src/ngsa-csharp/Ngsa.App/Core/CommandLine.cs
  src/ngsa-csharp/Ngsa.App/Core/NgsaLogExtensions.cs
  src/ngsa-csharp/Ngsa.App/Program.cs
  src/ngsa-csharp/Ngsa.DataService/Controllers/ActorsController.cs
  src/ngsa-csharp/Ngsa.DataService/Controllers/FeaturedController.cs
  src/ngsa-csharp/Ngsa.DataService/Controllers/GenresController.cs
  src/ngsa-csharp/Ngsa.DataService/Controllers/MoviesController.cs
  src/ngsa-csharp/Ngsa.DataService/Core/CommandLine.cs
  src/ngsa-csharp/Ngsa.DataService/Core/NgsaLogExtensions.cs
  src/ngsa-csharp/Ngsa.DataService/Program.cs
  src/ngsa-csharp/Ngsa.LodeRunner/Program.cs
  src/ngsa-csharp/Ngsa.LodeRunner/ValidationTest/Main.cs
  src/ngsa-csharp/Ngsa.Middleware/RequestLogger/RequestLogger.cs
Labels: FluentBit

#339 Update Arch MD
  docs/ApplicationArch.md
Labels: Documentation

#344 Doc updates
  IaC/AKS/README.md
  NewApp/ngsa-csharp/Ngsa.App/README.md
Labels: Documentation

#345 updated fluentbit config
  IaC/AKS/cluster/charts/fluentbit/templates/config.yaml
  IaC/DevCluster/fluentbit/loga-config.yaml
  IaC/DevCluster/fluentbit/stdout-config.yaml
Labels: FluentBit

#351 Load test
  IaC/DevCluster/app/in-memory.yaml
  IaC/DevCluster/app/new-in-memory.yaml
  IaC/DevCluster/app/ngsa-cosmos/new-ngsa.yaml
  IaC/DevCluster/app/ngsa-cosmos/ngsa.yaml
  IaC/LoadDemo/load-10.yaml
  IaC/LoadDemo/load-100.yaml
  IaC/LoadDemo/load-500.yaml
Labels: Bug, TestLoad, Testing:Load

#357 updated log setup
  src/Ngsa.App/Program.cs
  src/Ngsa.DataService/Program.cs
  src/Ngsa.Middleware/NgsaLog.cs
Labels: Bug

#361 updated to new container
  IaC/DevCluster/app/README.md
  IaC/DevCluster/app/ngsa-cosmos/README.md
  IaC/DevCluster/fluentbit/README.md
  IaC/DevCluster/loderunner/baseline-cosmos.yaml
  IaC/DevCluster/loderunner/baseline-memory.yaml
  IaC/DevCluster/loderunner/benchmark-cosmos.yaml
  IaC/DevCluster/loderunner/benchmark-memory.yaml
  IaC/DevCluster/loderunner/loderunner.yaml
Labels: Bug, Loderunner

#385 update packages and version
  src/Imdb.Model/Imdb.Model.csproj
  src/Ngsa.App.Tests/Ngsa.App.Tests.csproj
  src/Ngsa.App/Ngsa.App.csproj
  src/Ngsa.DataService.Tests/Ngsa.DataService.Tests.csproj
  src/Ngsa.DataService/Ngsa.DataService.csproj
  src/Ngsa.LodeRunner.Tests/Ngsa.LodeRunner.Tests.csproj
  src/Ngsa.LodeRunner/Ngsa.LodeRunner.csproj
  src/Ngsa.Middleware/Ngsa.Middleware.csproj
Labels: Release

#387 logging updates
  src/Ngsa.App/Controllers/ActorsController.cs
  src/Ngsa.App/Controllers/DataService.cs
  src/Ngsa.App/Controllers/FeaturedController.cs
  src/Ngsa.App/Controllers/GenresController.cs
  src/Ngsa.App/Controllers/MoviesController.cs
  src/Ngsa.App/Core/CommandLine.cs
  src/Ngsa.App/Program.cs
  src/Ngsa.DataService/Controllers/ActorsController.cs
  src/Ngsa.DataService/Controllers/FeaturedController.cs
  src/Ngsa.DataService/Controllers/GenresController.cs
  src/Ngsa.DataService/Controllers/MoviesController.cs
  src/Ngsa.DataService/Controllers/ResultHandler.cs
  src/Ngsa.DataService/Core/CommandLine.cs
  src/Ngsa.DataService/Program.cs
  src/Ngsa.LodeRunner.Tests/TestCommonValidator.cs
  src/Ngsa.Middleware/NgsaLog.cs
Labels: Release

#394 bill of materials
  docs/BoM.md
Labels: Documentation
