Repository retaildevcrews/ngsa, pull requests merged in 2021-04, with the labels that each got.

#651 Update onboarding documentation with links to new video location
  docs/Onboarding.md
Labels: Documentation

#643 Add Documentation for Azure Monitor for Containers
  spikes/oms-log-analytics/README.md
  spikes/oms-log-analytics/container-azm-ms-agentconfig.yaml
  spikes/oms-log-analytics/images/agent-logs.png
  spikes/oms-log-analytics/images/quantile-example-query.png
  spikes/oms-log-analytics/non-aks/0-crd.yaml
  spikes/oms-log-analytics/non-aks/1-clusterrole.yaml
  spikes/oms-log-analytics/non-aks/2-oms-rs-configmap.yaml
  spikes/oms-log-analytics/non-aks/4-daemonset.yaml
  spikes/oms-log-analytics/non-aks/5-deployment.yaml
  spikes/oms-log-analytics/non-aks/README.md
  spikes/oms-log-analytics/workspace-query-results.png
Labels: Documentation

#682 Scripts for mon-dev environment
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .gitignore
  IaC/PnP/monitoring/aks/README.md
  IaC/PnP/monitoring/aks/main.tf
  IaC/PnP/monitoring/aks/module.tf
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/01-terraform.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/02-aks.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/aad-pod-identity.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/akv-secrets-store-csi.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/container-azm-ms-agentconfig.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/flux.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/ingress-network-policy.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/kured-1.4.0-dockerhub.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/ns-a0008.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/agw/agw.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/agw/agw_application.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/agw/domain.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/aks.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/bastion/bastion.ignore
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/global_settings.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/iam/iam_aad.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/iam/iam_managed_identities.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/iam/iam_role_mappings.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/keyvault/certificate_requests.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/keyvault/keyvaults.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/monitor/diagnostics.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/monitor/log_analytics.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/firewall_application_rule_collection_definition.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/firewall_network_rule_collection_definition.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/firewalls.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/ip_groups.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/networking.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/nsg.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/peerings.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/private_dns.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/public_ips.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/route_tables.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/resource_groups.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/pictures/aks_enterprise_scale_lz.png
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/pictures/networking_configuration.PNG
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/pictures/ns-vwan.png
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/workloads/baseline/aspnetapp.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/workloads/baseline/traefik.yaml
  IaC/PnP/monitoring/aks/output.tf
  IaC/PnP/monitoring/aks/podidentity-assignment.tf
  IaC/PnP/monitoring/aks/provision-environment.sh
  IaC/PnP/monitoring/aks/variables.tf
  docs/Environment Strategy.pdf
  scripts/install_dev_tools.sh
Labels: FC:Monitoring, Infrastructure

#723 Add workbook for querying application metrics
  spikes/oms-log-analytics/README.md
  spikes/oms-log-analytics/azure-workbook.json
Labels: Documentation, FC:Monitoring

#711 NGSA-Memory deployment changes
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/ngsa-memory.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/workloads/baseline/traefik.yaml
Labels: FC:Monitoring, S:Large

#734 Added yaml files to create NGSA flux instance
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/ngsa-memory.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-settings/ngsa_memory_flux.yaml
Labels: CI-CD, DevExperience, Enhancement

#761 Updated Flux CD / GitOps instructions and path
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-settings/ngsa_memory_flux.yaml
Labels: CI-CD, DevExperience, Enhancement
