Repository retaildevcrews/ngsa, pull requests merged in 2021-08, with the labels that each got.

#662 Architecture diagrams
  .gitignore
  docs/arch/Azure-Native-Flow.drawio.svg
  docs/arch/Azure-Native.drawio.svg
  docs/arch/Azure-Native_Grafana.drawio.svg
  docs/arch/Azure-Prometheus_Grafana.drawio.svg
  docs/arch/Logical-1.drawio.svg
  docs/arch/Logical-CNCF.drawio.svg
  docs/arch/NGSA-dev.drawio.svg
  docs/arch/NGSA.vsdx
  docs/arch/prometheus-architecture.png
  docs/arch/readme.md
Labels: DesignReview

#792 Removed CAF related stuff
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  IaC/PnP/monitoring/aks/README.md
  IaC/PnP/monitoring/aks/main.tf
  IaC/PnP/monitoring/aks/module.tf
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/01-terraform.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/02-aks.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/aad-pod-identity.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/akv-secrets-store-csi.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/container-azm-ms-agentconfig.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/flux.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/ingress-network-policy.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/kured-1.4.0-dockerhub.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/cluster-baseline-settings/ns-a0008.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/agw/agw.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/agw/agw_application.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/agw/domain.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/aks.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/bastion/bastion.ignore
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/global_settings.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/iam/iam_aad.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/iam/iam_managed_identities.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/iam/iam_role_mappings.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/keyvault/certificate_requests.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/keyvault/keyvaults.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/monitor/diagnostics.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/monitor/log_analytics.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/firewall_application_rule_collection_definition.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/firewall_network_rule_collection_definition.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/firewalls.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/ip_groups.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/networking.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/nsg.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/peerings.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/private_dns.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/public_ips.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/networking/route_tables.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/configuration/resource_groups.tfvars
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/README.md
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-memory/ngsa-memory.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/ngsa-settings/ngsa_memory_flux.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/pictures/aks_enterprise_scale_lz.png
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/pictures/networking_configuration.PNG
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/pictures/ns-vwan.png
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/workloads/baseline/aspnetapp.yaml
  IaC/PnP/monitoring/aks/online/aks_secure_baseline/workloads/baseline/traefik.yaml
  IaC/PnP/monitoring/aks/output.tf
  IaC/PnP/monitoring/aks/podidentity-assignment.tf
  IaC/PnP/monitoring/aks/provision-environment.sh
  IaC/PnP/monitoring/aks/variables.tf
Labels: TechnicalDebt, S:XSmall, IaC, Infrastructure, WCNP

#793 Added Cluster ASB deployment files and instructions
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-install.sh
  .github/workflows/docker.yaml
  IaC/ASB/README.md
  IaC/ASB/cluster-stamp.json
  IaC/ASB/cosmos.md
  IaC/ASB/gitops/README.md
  IaC/ASB/gitops/cluster-baseline-settings/01-namespace.yaml
  IaC/ASB/gitops/cluster-baseline-settings/03-akv-secrets-store-csi.yaml
  IaC/ASB/gitops/cluster-baseline-settings/04-aad-pod-identity.yaml
  IaC/ASB/gitops/cluster-baseline-settings/05-kured.yaml
  IaC/ASB/gitops/ingress/01-namespace.yaml
  IaC/ASB/gitops/ingress/03-traefik.yaml
  IaC/ASB/gitops/kube-system/azm-agent-config.yaml
  IaC/ASB/gitops/ngsa/namespace.yaml
  IaC/ASB/gitops/ngsa/ngsa-memory.yaml
  IaC/ASB/networking/README.md
  IaC/ASB/networking/hub-default.json
  IaC/ASB/networking/hub-regionA.json
  IaC/ASB/networking/spoke-BU0001A0008.json
  IaC/ASB/networking/topology.md
  IaC/ASB/saveenv.sh
  IaC/ASB/templates/flux.yaml
  IaC/ASB/templates/load-test.yaml
  IaC/ASB/templates/ngsa-cosmos.yaml
  IaC/ASB/templates/ngsa-ingress.yaml
  IaC/ASB/templates/ngsa-pod-identity.yaml
  IaC/ASB/templates/traefik-config.yaml
  README.md
Labels: Infrastructure
