Repository retaildevcrews/ngsa, pull requests merged in 2021-02, with the labels that each got.

#426 Feature/lets encrypt docs
  IaC/AKS/README.md
  spikes/lets-encrypt/README.md
  spikes/lets-encrypt/prod-certificate.yaml
  spikes/lets-encrypt/prod-gateway.yaml
  spikes/lets-encrypt/staging-certificate.yaml
  spikes/lets-encrypt/staging-gateway.yaml
Labels: Documentation, IaC

#435 Added daily load test
  .github/workflows/loadTest.yaml
Labels: TestLoad, Testing:Load

#432 data service log bug
  src/Ngsa.App/Controllers/ActorsController.cs
  src/Ngsa.App/Controllers/FeaturedController.cs
  src/Ngsa.App/Controllers/GenresController.cs
  src/Ngsa.App/Controllers/MoviesController.cs
  src/Ngsa.App/Ngsa.App.csproj
  src/Ngsa.DataService/Controllers/ActorsController.cs
  src/Ngsa.DataService/Controllers/FeaturedController.cs
  src/Ngsa.DataService/Controllers/GenresController.cs
  src/Ngsa.DataService/Controllers/MoviesController.cs
  src/Ngsa.DataService/Core/CommandLine.cs
  src/Ngsa.DataService/Ngsa.DataService.csproj
  src/Ngsa.DataService/Program.cs
  src/Ngsa.LodeRunner/Ngsa.LodeRunner.csproj
  src/Ngsa.Middleware/Ngsa.Middleware.csproj
  src/Ngsa.Middleware/NgsaLog.cs
Labels: Bug, DataService

#450 Updating GH action to use RDC org #449
  .github/workflows/scheduled_mdlinkcheck.yaml
Labels: Documentation

#446 Migrated ngsa-cd repo to ngsa
  gitops/README.md
  gitops/charts/fluentbit/.helmignore
  gitops/charts/fluentbit/Chart.yaml
  gitops/charts/fluentbit/templates/NOTES.txt
  gitops/charts/fluentbit/templates/_helpers.tpl
  gitops/charts/fluentbit/templates/config-log.yaml
  gitops/charts/fluentbit/templates/config.yaml
  gitops/charts/fluentbit/templates/daemonset.yaml
  gitops/charts/fluentbit/templates/role.yaml
  gitops/charts/fluentbit/values.yaml
  gitops/charts/ngsa/.helmignore
  gitops/charts/ngsa/Chart.yaml
  gitops/charts/ngsa/helm-config.example.yaml
  gitops/charts/ngsa/templates/_helpers.tpl
  gitops/charts/ngsa/templates/certificate.yaml
  gitops/charts/ngsa/templates/configmap.yaml
  gitops/charts/ngsa/templates/deployment.yaml
  gitops/charts/ngsa/templates/scaledobject.yaml
  gitops/charts/ngsa/templates/service.yaml
  gitops/charts/ngsa/templates/serviceaccount.yaml
  gitops/charts/ngsa/templates/virtualservice.yaml
  gitops/charts/ngsa/values.yaml
  gitops/deployments/dev/gateway.yaml
  gitops/deployments/dev/loderunner.yaml
  gitops/deployments/dev/ngsa-cosmos.yaml
  gitops/deployments/dev/ngsa-memory.yaml
  gitops/deployments/preprod/central/fluentbit.yaml
  gitops/deployments/preprod/central/ngsa-cosmos.yaml
  gitops/deployments/preprod/central/ngsa-memory.yaml
  gitops/deployments/preprod/common/gateway.yaml
  gitops/deployments/preprod/common/loderunner.yaml
  gitops/deployments/preprod/east/fluentbit.yaml
  gitops/deployments/preprod/east/ngsa-cosmos.yaml
  gitops/deployments/preprod/east/ngsa-memory.yaml
  gitops/deployments/preprod/west/fluentbit.yaml
  gitops/deployments/preprod/west/ngsa-cosmos.yaml
  gitops/deployments/preprod/west/ngsa-memory.yaml
Labels: CI-CD, CI/CD, IaC

#447 Add sprint tracker template #443
  .github/ISSUE_TEMPLATE/sprint-tracker.md
Labels: Process

#442 add prometheus to dev cluster
  IaC/DevCluster/README.md
  IaC/DevCluster/app/README.md
  IaC/DevCluster/app/in-memory.yaml
  IaC/DevCluster/app/new-memory.yaml
  IaC/DevCluster/app/ngsa-cosmos/ngsa.yaml
  IaC/DevCluster/dashboards/dotnet.json
  IaC/DevCluster/dashboards/ngsa.json
  IaC/DevCluster/fluentbit/loga-config.yaml
  IaC/DevCluster/fluentbit/stdout-config.yaml
  IaC/DevCluster/grafana/datasource.yaml
  IaC/DevCluster/grafana/deployment.yaml
  IaC/DevCluster/grafana/service.yaml
  IaC/DevCluster/kube-state-metrics/cluster-role-binding.yaml
  IaC/DevCluster/kube-state-metrics/cluster-role.yaml
  IaC/DevCluster/kube-state-metrics/deployment.yaml
  IaC/DevCluster/kube-state-metrics/service-account.yaml
  IaC/DevCluster/kube-state-metrics/service.yaml
  IaC/DevCluster/loderunner/baseline-cosmos.yaml
  IaC/DevCluster/loderunner/baseline-memory.yaml
  IaC/DevCluster/loderunner/benchmark-cosmos.yaml
  IaC/DevCluster/loderunner/benchmark-memory.yaml
  IaC/DevCluster/loderunner/loderunner.yaml
  IaC/DevCluster/ngsa-cosmos/README.md
  IaC/DevCluster/ngsa-cosmos/ngsa-cosmos.yaml
  IaC/DevCluster/ngsa-memory/README.md
  IaC/DevCluster/ngsa-memory/ngsa-memory.yaml
  IaC/DevCluster/prometheus/1-clusterRole.yaml
  IaC/DevCluster/prometheus/2-config-map.yaml
  IaC/DevCluster/prometheus/3-prometheus-deployment.yaml
  IaC/DevCluster/prometheus/4-prometheus-service.yaml
  README.md
Labels: DesignReview, Observability

#467 Fixed dead links in repository
  IaC/AKS/README.md
  spikes/ngsa-typescript/README.md
Labels: Bug, Documentation

#468 Dev Cluster Setup
  IaC/DevCluster/README.md
  IaC/DevCluster/grafana/namespace.yaml
  IaC/DevCluster/grafanadata/grafana.db
  IaC/DevCluster/ngsa-cosmos/README.md
  IaC/DevCluster/ngsa-cosmos/ngsa-cosmos.yaml
  IaC/DevCluster/ngsa-memory/README.md
  IaC/DevCluster/prometheus/1-clusterRole.yaml
  IaC/DevCluster/prometheus/2-config-map.yaml
Labels: Bug

#481 Patched from "bugfix/fluentbit-mem-buf-fix" in ngsa-cd repo
  gitops/charts/fluentbit/templates/config.yaml
Labels: Bug, FluentBit, PointDev

#484 updated to run on ubuntu 20.04
  .github/workflows/loadTest.yaml
  .github/workflows/mdlinkcheck.yaml
  .github/workflows/scheduled_mdlinkcheck.yaml
  IaC/AKS/README.md
  IaC/AKS/cluster/charts/loderunner/templates/deployment.yaml
  IaC/AKS/scripts/create-cluster-env.bash
  IaC/LoadDemo/load-100.yaml
  IaC/LoadDemo/load-200.yaml
  IaC/LoadDemo/load-50.yaml
Labels: CI-CD

#483 added dev cluster cheat sheet
  IaC/DevCluster/cheatsheet.txt
Labels: DevExperience, Documentation
